/**
 * Feature flags (brief §5.7, §10.2). Defaults follow the approved proposals:
 * no stats row (P3), analytics off until real IDs exist, prices on.
 */

export const flags = {
  /** SHOW_PRICES=false renders "Minta estimasi" instead of every price. */
  SHOW_PRICES: true,
  /** Availability pill in the header; hidden entirely when false. */
  SHOW_AVAILABILITY: true,
  /** Analytics is off until a real GA4 / Meta Pixel ID is provided (see analytics.ts). */
  ENABLE_ANALYTICS: false,
  /** ⌘K command palette (built in M5). */
  ENABLE_COMMAND_PALETTE: true,
  /** Film grain texture layer. */
  SHOW_GRAIN: true,
  /** Stats/counter row — no real numbers provided, so it is off (proposal P3). */
  SHOW_STATS: false,
  /** Price list PDF button; the file is generated by scripts/generate-price-list.ts. */
  SHOW_PRICELIST_PDF: true,
} as const;

export type Flags = typeof flags;
export type FlagName = keyof Flags;
